Custom junit formatting
Chekote/Behat pull request #3
Opened 2022-07-05 18:57 UTC by lorenzodalaqua

This PRs customizes the title of a Scenario and other attributes when formatting test output using the `junit` format.

It mainly adds the line number and CircleCI node number to the scenario title.

EDIT: I ended up only adding any attributes if the `CIRCLE_NODE_INDEX` env variable is set. This way, tests in this project will not have to be affected, and I updated tests that use this patched version to set that variable when the added attributes are needed.

2022-07-05 19:46 UTC, Chekote requested changes
I've also asked @BKorenek to weigh in on this and confirm that his concerns about navigating have been addressed.

2022-07-05 19:46 UTC, Chekote commented on src/Behat/Behat/Output/Node/Printer/JUnit/JUnitScenarioPrinter.php
> +        return $name . " Line #" . $lineNumber;
Double quotes are necessary if you don't need string interpolation.
But I feel like if we use string interpolation, we can actually simplify this:

```suggestion
        return "$name Line #$lineNumber";
```

Please do this for similar string concatenation in this PR.

2022-07-05 19:46 UTC, Chekote commented on src/Behat/Behat/Output/Node/Printer/JUnit/JUnitScenarioPrinter.php
> +    }
Please put a blank line between methods.

2022-07-05 19:46 UTC, Chekote commented on src/Behat/Behat/Output/Node/Printer/JUnit/JUnitScenarioPrinter.php
> +     * @param string $path
Let's either add a description to this or tweak the method description to be more obvious:

```suggestion
     * @param string $path the path to the feature file
```

```
     * Append the line number of the scenario within the feature file to the feature file's path
```

2022-07-05 19:46 UTC, Chekote commented on src/Behat/Behat/Output/Node/Printer/JUnit/JUnitScenarioPrinter.php
> +        if($circleCiNode !== false) {
```suggestion
        if ($circleCiNode !== false) {
```

2022-07-05 19:46 UTC, Chekote commented on src/Behat/Behat/Output/Node/Printer/JUnit/JUnitScenarioPrinter.php
> +            $attributes['name'] = $circleCiNodeLabel . $attributes['name'];
The `$circleCiNodeLabel` variable seems unnecessary:

```suggestion
            $attributes['name'] = "[Node #$circleCiNode] ${attributes['name']}";
```

2022-07-05 21:17 UTC, BKorenek approved these changes
I'm not super familiar with how this is all set up or exactly how it would translate, but at a glance it seems like ti would be good. The title is on its own from what I can tell, so it can be copied exactly and fed into `behat --name="<paste>"` and in addition the file and line number are dropped on there own line, pending donalds review being address it seems, which can also be used as `behat <paste>`. I'm a happy camper.

2022-07-05 21:55 UTC, lorenzodalaqua commented on src/Behat/Behat/Output/Node/Printer/JUnit/JUnitScenarioPrinter.php
> +     * @param string $path
I renamed this method and updated the comments to make it clearer what it is doing.

2022-07-06 14:29 UTC, Chekote commented on src/Behat/Behat/Output/Node/Printer/JUnit/JUnitScenarioPrinter.php
> +        $name = $currentOutline->getTitle();
Why is this being removed? It seems to be part of Behat's normal behavior.

2022-07-06 15:42 UTC, lorenzodalaqua commented on src/Behat/Behat/Output/Node/Printer/JUnit/JUnitScenarioPrinter.php
> +        $name = $currentOutline->getTitle();
Yeah, it is, I had forgotten about this modification. This is Behat normal behaviour, I added it back and will remove it only on CI.

This broke our automation script because when we run Behat a second time time with the `--rerun` flag all examples in a scenario outline would have `#1` in their title instead of the correct index. So if the second example failed in the first Behat run, in the rerun it would have a different title (e.g Scenario Title #2 would become Scenario Title #1 in the rerun).

I believe this happens because only the failing example is executed in the rerun and the way this method works is to keep a count of scenarios run with the same title, or maybe they are run in a different order in a rerun.

2022-07-06 18:35 UTC, Chekote commented on src/Behat/Behat/Output/Node/Printer/JUnit/JUnitScenarioPrinter.php
> +        $name = $currentOutline->getTitle();
What do you think about this:

Instead of removing data from the normal Behat output, what amount moving this concern to the IFT automation script itself and leaving this as-is? The IFT automation script can strip the suffix off the end. That way, we can keep the modification of Behat to a minimum.

2022-07-06 18:49 UTC, lorenzodalaqua commented on src/Behat/Behat/Output/Node/Printer/JUnit/JUnitScenarioPrinter.php
> +        $name = $currentOutline->getTitle();
Makes sense, I'll modify it in STDCheck and remove this here.

2022-07-06 20:17 UTC, Chekote approved these changes

2022-07-06 20:20 UTC, merged